name: Github Pages

on:
  push:
    branches:
      - main # Change this to your default branch if it's different
permissions:
  contents: write

jobs:
  pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: |
          npm run build
          cp CNAME ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
